name: Publish

on:
  pull_request:
    branches: [release]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
      # If deploy release version, add option "npm publish --access=public"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
